### ISSUE TITLE
Amend website along lines of what has been shared via email

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/leeds-schools-cultural-engagement#11]
To include in a footer

- [x] Attached logo
- [x] Statement that "This work was supported by Research England under the Policy Support funding stream."

![Image](https://user-images.githubusercontent.com/88284441/235942706-28b6e9d6-06d5-4e1f-8e73-3ff9c4b6a48a.png)

**Comment by luke-strange** [comment]
I don't have this repo cloned and am not familiar with the layout so probably much quicker for @taz-chiles to do this job, but can pick-up if needed.

**Comment by taz-chiles** [comment]
All good, @ODILMichelle can we grab 5 minutes to talk about this one?

**Comment by ODILMichelle** [comment]
For sure - I'm still handing around on Gather
________________________________

**Comment by taz-chiles** [comment]
I've added the logo and text the footer, however ideally need an inverted version of the logo as it blends in with the background. 
Let me know any changes @ODILMichelle

**Comment by ODILMichelle** [comment]
The logo looks a little pinched to me? I will send over the logo via email, and perhaps just check the ratio on what we're uploading?

**Comment by taz-chiles** [comment]
I've made the image slightly larger (should be able to see in a couple of mins) - I think that looks better although still dark on dark background

**Comment by ODILMichelle** [comment]
Thanks for this @taz-chiles - looks like the ratio has been kept from the original image now. Is that correct?

And just before moving this into done, it looks like there are some dashes above and below the image oddly? Or is that just on my screen..?

**Comment by taz-chiles** [comment]
@ODILMichelle I have removed the dashes - can this be closed?
