### ISSUE TITLE
Map the schools of Leeds

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/leeds-schools-cultural-engagement#17]
Layer per type

**Comment by gilesdring** [comment]
I think this is done @slowe / @ODILMichelle

**Comment by taz-chiles** [comment]
@ODILMichelle assuming this refers to https://open-innovations.github.io/leeds-schools-cultural-engagement/reports/schools/

Can this now be closed?

**Comment by taz-chiles** [comment]
Have discussed with @ODILMichelle, closing as completed and will pick up amendments in a new ticket.
