### ISSUE TITLE
Create csv of schools in Leeds & their characteristics

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/leeds-schools-cultural-engagement#22]

**Comment by ODILMichelle** [comment]
Pre-reqs for final version:

- [ ] Confirming school type buckets

**Comment by gilesdring** [comment]
@ODILMichelle will upload and share link in here.

**Comment by gilesdring** [comment]
Put in top-level `data` directory in https://github.com/open-innovations/leeds-schools-cultural-engagement/tree/main. Remove any non-publishable data columns (e.g. survey responses or not) and any dates.

**Comment by ODILMichelle** [comment]
Should be done now @slowe @gilesdring

**Comment by slowe** [comment]
I'm also downloading the latest data from https://get-information-schools.service.gov.uk/Downloads to compare/contrast.

**Comment by slowe** [comment]
I'm also going to note (mostly for myself) that https://github.com/open-innovations/west-yorkshire-mapping/blob/main/data/leeds/leeds-amenities-school.geojson may be useful for polygons.

**Comment by gilesdring** [comment]
Closing as done???
