### ISSUE TITLE
Upload anonymised and processed survey response analysis to github

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/leeds-schools-cultural-engagement#27]
Upload a dataset derived from survey responses, but anonymised / summarised / analysed. Place this in CSV format in the top-level `data` directory.

**Comment by taz-chiles** [comment]
@ODILMichelle  does this refer to the survey response data that has been added and visualised from this directory? If so, can this be closed?

https://github.com/open-innovations/leeds-schools-cultural-engagement/tree/main/src/_data/viz

**Comment by taz-chiles** [comment]
Closing #27
