### ISSUE TITLE
Create visualisations of survey response analysis

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/leeds-schools-cultural-engagement#28]

**Comment by gilesdring** [comment]
Depends on #27 and #24

**Comment by taz-chiles** [comment]
@ODILMichelle does this ticket refer to the visualisations that have been added to this page: 

https://open-innovations.github.io/leeds-schools-cultural-engagement/reports/survey/

If so, can this be closed?

**Comment by taz-chiles** [comment]
After chatting with @ODILMichelle, this is done for now - closing #28
