### ISSUE TITLE
Review fonts for Leeds Cultural Engagement site

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/leeds-schools-cultural-engagement#30]
Look into whether we can use the font shared with us by UofL - the same as the ‘Mapping creative education’ logo

They may need to tell us what the font is, or provide us with the packages. This may not be possible, and we can stick with Poppins if so or use another font that is similar.

**Comment by slowe** [comment]
Having managed to find the logo font ([Bungee Hairline](https://fonts.google.com/specimen/Bungee+Hairline)) it was decided that this typeface doesn't work for headings - they look really thin. Instead the decision was taken to use [Titillium Web](https://fonts.google.com/specimen/Titillium+Web) which is also released under an Open Font Licence but looks better in headings.
